name: Deploy Backend to Synology

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'backend/server.js'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Deploy to Synology
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SYNOLOGY_HOST }}
          username: ${{ secrets.SYNOLOGY_USERNAME }}
          password: ${{ secrets.SYNOLOGY_PASSWORD }}
          port: ${{ secrets.SYNOLOGY_SSH_PORT }}
          script: |
            export PATH="/usr/local/bin:$PATH"
            cd /volume1/docker2/easymemo-backend

            # 중요 파일 백업
            cp docker-compose.yml docker-compose.yml.backup
            cp .env .env.backup

            # git 저장소가 없는 경우 초기화
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/whwnddml/easy-memo.git
            fi

            # 현재 변경사항 스태시
            git stash

            # 최신 코드 가져오기 (backend 폴더만)
            git fetch origin
            git checkout origin/main -- backend/

            # 백업했던 파일 복원
            mv docker-compose.yml.backup docker-compose.yml
            mv .env.backup .env

            # 스태시 적용
            #git stash pop

            # Docker 재시작
            /usr/local/bin/docker-compose stop
            /usr/local/bin/docker-compose up -d --build